### ISSUE TITLE
issues作成テストもかねて、各ラベルの意味

### ISSUE THREAD

**Issue by TokisaSigure** [Kiefer7126/RhythWalk#12]
issues作成のテストも兼ねて各ラベルの意味をメモ書きしておきます。
(本来ならwikiにかくべきかも？？)
1. bug                   意味：バグ
2. duplicate           意味：重複
3. enhancement   意味：強化 (意訳:この機能強化しようぜ！)
4. invalid               意味：報告の間違い
5. question            意味：質問
6. wontfix              意味：対処しない(バグってるけど、これ仕様だから気にしないでね！)
7.help wanted       意味:求人広告(意訳:ここ詰まってるんだけど、何か良い意見ないかな？)

こんな感じです。
間違えても問題は無いですが、リストで見た際に分かりやすいので、意識して貰えるとうれしいかも？
(issuesの強化の意を込めて、今回は[enhancement])
参照URL: http://xtendsmyblog.blogspot.jp/2012/11/githubissues.html

**Comment by TokisaSigure** [comment]
間違えていらないラベル追加してたので、外しておきました。

**Comment by Kiefer7126** [comment]
一人でやっていたということもあって、wontfixを「とりあえずそのうちやろうと思っていたToDo」をメモ的な意味で使っていましたが、変えたほうがよさそうですね。とりあえずラベルが追加できるようなので"Sometime"を追加してみました。
