### ISSUE TITLE
端末内楽曲リスト取得について

### ISSUE THREAD

**Issue by mikankari** [Kiefer7126/RhythWalk#13]
リスト取得は未実装なのでしょうか。
PrepareMusicRetrieverTask.javaあたりがそうだと思いましたが、取得手段なさそうだし、使ってないようにも思えます

**Comment by Kiefer7126** [comment]
僕の端末ではローカルの音楽ファイルのリスト取得はできています。Itemクラスですができていませんか？

**Comment by mikankari** [comment]
Itemのstaticメソッドでしたか。失礼しました。ありがとうございます
